version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    environment:
      - NODE_ENV=
      - MONGO_URI=
      - JWT_SECRET_KEY=
      - JWT_EXPIRE=
      - CLOUDINARY_CLOUD_NAME=
      - CLOUDINARY_API_KEY=
      - CLOUDINARY_API_SECRET=
      - COOKIE_EXPIRE=
      - SMTP_HOST=
      - SMTP_SERVICE=
      - SMTP_PORT=
      - SMTP_MAIL=
      - SMTP_PASSWORD=
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: